import { WidgetType } from '@/types/widget';
import type { PlanConfig } from './types';

export const premiumPlanConfig: PlanConfig = {
  id: 'PREMIUM',
  slug: 'premium',
  name: 'Premium',
  description: 'Full access to every widget, limit, and premium perk.',
  monthlyPrice: 5.99,
  monthlyPriceLabel: '€5.99',
  ctaLabel: 'Go Premium',
  highlight: 'premium',
  featureList: [
    'Unlimited dashboard widgets',
    'All widgets including Absence Recommender',
    'Premium themes',
    'Priority support',
    'Data export and early access',
  ],
  features: {
    maxWidgets: null,
    allowedWidgetTypes: [
      WidgetType.KPI_7DAYS,
      WidgetType.KPI_14DAYS,
      WidgetType.KPI_30DAYS,
      WidgetType.KPI_ALLTIME,
      WidgetType.ABSENCE_BAR,
      WidgetType.ABSENCE_TREND,
      WidgetType.SUBJECT_BREAKDOWN,
      WidgetType.ABSENCE_RECOMMENDER,
      WidgetType.TOTAL_ABSENCE_BAR,
      WidgetType.ABSENCE_RATE,
    ],
    statisticsRangeDays: null,
    themes: 'premium',
    dataExport: true,
    prioritySupport: true,
    earlyAccess: true,
    advancedAnalytics: true,
    customLayouts: true,
  },
  comparison: {
    dashboardWidgets: 'Unlimited',
    widgetTypes: 'All widgets',
    themes: 'Premium',
    statisticsRange: 'Unlimited',
    dataExport: 'Yes',
    prioritySupport: 'Yes',
    earlyAccess: 'Yes',
  },
};
