import { WidgetType } from "@/types/widget";
import type { PlanConfig } from "./types";

export const premiumPlanConfig: PlanConfig = {
    id: "PREMIUM",
    slug: "premium",
    name: "Premium",
    description: "Voller Zugriff auf jedes Widget, jede Grenze und jeden Premium-Vorteil.",
    monthlyPrice: 5.99,
    monthlyPriceLabel: "€5.99",
    yearlyPrice: 59.99,
    yearlyPriceLabel: "€59.99",
    yearlySavings: "17% sparen",
    ctaLabel: "Auf Premium upgraden",
    highlight: "premium",
    featureList: [
        "Unbegrenzte Dashboard-Widgets",
        "Alle Widgets inkl. Fehlzeiten-Empfehlung",
        "Premium-Themes",
        "Prioritäts-Support",
        "Datenexport und Frühzugriff",
    ],
    features: {
        maxWidgets: null,
        allowedWidgetTypes: [
            WidgetType.KPI_7DAYS,
            WidgetType.KPI_14DAYS,
            WidgetType.KPI_30DAYS,
            WidgetType.KPI_ALLTIME,
            WidgetType.ABSENCE_BAR,
            WidgetType.ABSENCE_TREND,
            WidgetType.SUBJECT_BREAKDOWN,
            WidgetType.ABSENCE_RECOMMENDER,
            WidgetType.TOTAL_ABSENCE_BAR,
            WidgetType.ABSENCE_RATE,
        ],
        statisticsRangeDays: null,
        themes: "premium",
        dataExport: true,
        prioritySupport: true,
        earlyAccess: true,
        advancedAnalytics: true,
        customLayouts: true,
    },
    comparison: {
        dashboardWidgets: "Unbegrenzt",
        widgetTypes: "Alle Widgets",
        themes: "Premium",
        statisticsRange: "Unbegrenzt",
        dataExport: "Ja",
        prioritySupport: "Ja",
        earlyAccess: "Ja",
    },
};
