import { WidgetType } from "@/types/widget";
import type { PlanConfig } from "./types";

export const standardPlanConfig: PlanConfig = {
    id: "STANDARD",
    slug: "standard",
    name: "Standard",
    description: "Mehr Platz für Dashboards und reichhaltigere Analysen für den Tag.",
    monthlyPrice: 3.99,
    monthlyPriceLabel: "€3.99",
    yearlyPrice: 39.99,
    yearlyPriceLabel: "€39.99",
    yearlySavings: "15% sparen",
    ctaLabel: "Auf Standard upgraden",
    highlight: "popular",
    featureList: [
        "Bis zu 10 Dashboard-Widgets",
        "Alle Kern-Widgets mit höheren Grenzen",
        "Standard-Themes",
        "Erweiterte Analyseübersicht",
        "Benutzerdefinierte Dashboard-Layouts",
    ],
    features: {
        maxWidgets: 10,
        allowedWidgetTypes: [
            WidgetType.KPI_7DAYS,
            WidgetType.KPI_14DAYS,
            WidgetType.KPI_30DAYS,
            WidgetType.KPI_ALLTIME,
            WidgetType.ABSENCE_BAR,
            WidgetType.ABSENCE_TREND,
            WidgetType.SUBJECT_BREAKDOWN,
            WidgetType.TOTAL_ABSENCE_BAR,
            WidgetType.ABSENCE_RATE,
        ],
        statisticsRangeDays: 90,
        themes: "standard",
        dataExport: false,
        prioritySupport: false,
        earlyAccess: false,
        advancedAnalytics: true,
        customLayouts: true,
    },
    comparison: {
        dashboardWidgets: "Bis zu 10",
        widgetTypes: "Kern-Widgets",
        themes: "Standard",
        statisticsRange: "90 Tage",
        dataExport: "Nein",
        prioritySupport: "Nein",
        earlyAccess: "Nein",
    },
};
