import { WidgetType } from '@/types/widget';
import type { PlanConfig } from './types';

export const standardPlanConfig: PlanConfig = {
  id: 'STANDARD',
  slug: 'standard',
  name: 'Standard',
  description: 'More room for dashboards and richer day-to-day analytics.',
  monthlyPrice: 3.99,
  monthlyPriceLabel: '€3.99',
  ctaLabel: 'Go Standard',
  highlight: 'popular',
  featureList: [
    'Up to 10 dashboard widgets',
    'All core widgets with higher limits',
    'Standard themes',
    'Advanced analytics overview',
    'Custom dashboard layouts',
  ],
  features: {
    maxWidgets: 10,
    allowedWidgetTypes: [
      WidgetType.KPI_7DAYS,
      WidgetType.KPI_14DAYS,
      WidgetType.KPI_30DAYS,
      WidgetType.KPI_ALLTIME,
      WidgetType.ABSENCE_BAR,
      WidgetType.ABSENCE_TREND,
      WidgetType.SUBJECT_BREAKDOWN,
      WidgetType.TOTAL_ABSENCE_BAR,
      WidgetType.ABSENCE_RATE,
    ],
    statisticsRangeDays: 90,
    themes: 'standard',
    dataExport: false,
    prioritySupport: false,
    earlyAccess: false,
    advancedAnalytics: true,
    customLayouts: true,
  },
  comparison: {
    dashboardWidgets: 'Up to 10',
    widgetTypes: 'Core widgets',
    themes: 'Standard',
    statisticsRange: '90 days',
    dataExport: 'No',
    prioritySupport: 'No',
    earlyAccess: 'No',
  },
};
